baseURL = 'https://Andrei-Constantin-Programmer.github.io/ibm-ucl-blog/'
languageCode = 'en-gb'
title = 'LLM-Powered Legacy Code Refactoring'
theme = "PaperMod"
defaultContentLanguage = "en"
enableInlineShortcodes = true

[params]
    mainSections = ["posts", "project", "team"]
    ShowBreadCrumbs = true
    ShowReadingTime = true
    ShowPostNavLinks = true
    ShowCodeCopyButtons = true
    defaultTheme = "auto"

[pagination]
    pagerSize = 5

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 2

[[menu.main]]
  name = "Project"
  url = "/project"
  weight = 3

[[menu.main]]
  name = "Team"
  url = "/team"
  weight = 4

[params.assets]
  customCSS = [
    "https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css",
    "css/glightbox-custom.css"
  ]
  customJS  = [
    "https://cdn.jsdelivr.net/npm/glightbox/dist/js/glightbox.min.js",
    "js/init-glightbox.js"
  ]
